
VERILOG_SOURCES= modulator.v ../counter/module_counter.v ../counter/counter.v
MODULE=test
TOPLEVEL=modulator
include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
