`ifndef __PROJECT_CONFIG_V
`define __PROJECT_CONFIG_V

`define PARAMETER01 1200
`define PARAMETER02 12
`define PARAMETER03 24
`define PARAMETER04 0

`define MODULATION  5

`define CLK_PERIOD  4

`endif